# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20170504_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='centres',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
    ]
