# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20170502_1256'),
        ('facilities', '0003_centres_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_facilitysubtype', to='masterdata.MasterLookUp'),
        ),
    ]
