# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20170502_1256'),
        ('service', '0002_service'),
        ('facilities', '0004_facility_facility_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='services',
            field=models.ManyToManyField(blank=True, to='service.Service'),
        ),
        migrations.AddField(
            model_name='facility',
            name='thematic_area',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='facility_thematicarea', to='masterdata.MasterLookUp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_facilitytype', to='masterdata.MasterLookUp'),
        ),
    ]
