# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_auto_20170424_0654'),
        ('partner', '0005_project_boundary'),
        ('facilities', '0005_auto_20170505_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_beneficiary', to='beneficiary.Beneficiary'),
        ),
        migrations.AddField(
            model_name='facility',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_partner', to='partner.Partner'),
        ),
    ]
