# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_auto_20170508_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='btype',
            field=models.CharField(choices=[('Household', 'Household'), ('Mother', 'Mother'), ('Child', 'Child')], default=datetime.datetime(2017, 5, 9, 5, 49, 18, 199174, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
