# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('facilities', '0008_auto_20170510_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('prefix_type', models.CharField(choices=[('Non-Financial', 'Non-Financial'), ('Financial', 'Financial')], default='Non-Financial', max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('separator', models.CharField(blank=True, max_length=100, null=True)),
                ('padlength', models.PositiveIntegerField(blank=True, null=True)),
                ('start_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
