# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('facilities', '0009_codeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeconfig',
            name='ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeconfig_ctype', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='codeconfig',
            name='for_object',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codeconfig',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codeconfig',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codeconfig',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeconfig_mainctype', to='contenttypes.ContentType'),
        ),
    ]
