# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_auto_20170706_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeconfig',
            name='sequence',
            field=models.BooleanField(default=False),
        ),
    ]
