# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_codeconfig_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID'),
        ),
    ]
