# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20171130_1114'),
        ('facilities', '0015_facility_tempid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_facilit', to='partner.Partner'),
        ),
        migrations.RemoveField(
            model_name='facility',
            name='thematic_area',
        ),
        migrations.AddField(
            model_name='facility',
            name='thematic_area',
            field=models.ManyToManyField(related_name='facility_thematicarea', to='masterdata.MasterLookUp'),
        ),
    ]
