# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-05-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0019_facilitybeneficiarydeactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybeneficiarydeactivate',
            name='action',
            field=models.PositiveIntegerField(choices=[(0, 'Created'), (1, 'Deleted'), (2, 'Updated'), (3, 'Activated'), (4, 'Deactivated'), (5, 'Others')], default=5),
        ),
    ]
