from django.conf.urls import url
from .views import (
    PartnerName, PartnerDetailCreate, PartnerListingMasterLookUp,
    ProjectDetailsCreate, ProjectHolderCreate, PartnerAddressCreate, ProjectLocationListing,
    RegistrationCreate, BankAccountCreate, PartnerList, PartnerActions, RegistrationList,
    BankAccountList, AddressListing, PartnerViewDetail, RegistrationViewDetail,
    BankViewDetail, AddressViewDetail,
    ProjectList, ProgramList, ProjectViewDetail, ProgramViewDetail, CustomProjectListing,
    ProjectHolderDetailView,
    GetPriority, AddressEdit, RegistrationEdit, BankAccountEdit, PartnerNewEdit,
    PartnerProjectLocationEdit, ProjectHolderEdit,
    AllModuleActions, ProjectLocationDetail, PartnerEmployee,
    PartnerEmployeeListing,StateRelatedPartner,CreatePartnerUserInfo,PartnerDatabase,
    PartnerUserInfoDetail,PartnerUserInfoList,NatureOfPartnerList)
from .dpf_view import (
    DonarCreate, DonarDetailView, DonarListing, GetDateToYear, GetThematic,
    ItemLineChecker,
    BudgetConfigCreate, BudgetConfigListing, BudgetConfigEdit, FundingCreate,
    FundingThematicListing, FundingYearListing,
    FundingListing, FundingDetailView, DPFProjectViewDetail, GetDateToYearPartner
)
from .partner_report import (
    PartnerReportTable, PartnerDownloadReport, DPFilterData)
from .create_db import export_db
urlpatterns = [
    url(r'^name/create/$', PartnerName.as_view()),
    url(r'^edit/(?P<pk>[0-9]+)/$', PartnerNewEdit.as_view()),
    url(r'^details/create/$', PartnerDetailCreate.as_view()),
    url(r'^masterlookup/listing/$', PartnerListingMasterLookUp.as_view()),
    url(r'^project/create/$', ProjectDetailsCreate.as_view()),
    url(r'^project/location/detail/$', ProjectLocationListing.as_view()),
    url(r'^project/location/view/$', ProjectLocationDetail.as_view()),
    url(r'^project/location/edit/$', PartnerProjectLocationEdit.as_view()),
    url(r'^project/holder/$', ProjectHolderCreate.as_view()),
    url(r'^project/holder/view/$', ProjectHolderDetailView.as_view()),
    url(r'^project/holder/edit/$', ProjectHolderEdit.as_view()),
    url(r'^address/$', PartnerAddressCreate.as_view()),
    url(r'^address/edit/(?P<pk>[0-9]+)/$', AddressEdit.as_view()),
    url(r'^registration/$', RegistrationCreate.as_view()),
    url(r'^registration/edit/(?P<pk>[0-9]+)/$', RegistrationEdit.as_view()),
    url(r'^bank/$', BankAccountCreate.as_view()),
    url(r'^bank/edit/(?P<pk>[0-9]+)/$', BankAccountEdit.as_view()),
    url(r'^list/$', PartnerList.as_view()),
    url(r'^actions/$', PartnerActions.as_view()),
    url(r'^registration/list/$', RegistrationList.as_view()),
    url(r'^bank/list/$', BankAccountList.as_view()),
    url(r'^address/list/$', AddressListing.as_view()),
    url(r'^details/$', PartnerViewDetail.as_view()),
    url(r'^registration/details/$', RegistrationViewDetail.as_view()),
    url(r'^bank/details/$', BankViewDetail.as_view()),
    url(r'^address/details/$', AddressViewDetail.as_view()),
    url(r'^project/listing/$', CustomProjectListing.as_view()),
    url(r'^project/$', ProjectList.as_view()),
    url(r'^project/details/(?P<pk>[0-9]+)/$', ProjectViewDetail.as_view()),
    url(r'^program/$', ProgramList.as_view()),
    url(r'^program/details/(?P<pk>[0-9]+)/$', ProgramViewDetail.as_view()),
    url(r'^priority/list/$', GetPriority.as_view()),
    url(r'^module/action/$', AllModuleActions.as_view()),
    url(r'^employee/list/$', PartnerEmployeeListing.as_view()),
    url(r'^dfp/donar/$', DonarCreate.as_view()),
    url(r'^dfp/donar/listing/$', DonarListing.as_view()),
    url(r'^dfp/donar/detail/(?P<pk>[0-9]+)/$', DonarDetailView.as_view()),
    url(r'^dfp/get-year/$', GetDateToYear.as_view()),
    url(r'^dfp/get-themactics/$', GetThematic.as_view()),
    url(r'^dfp/item-line/checker/$', ItemLineChecker.as_view()),
    url(r'^dfp/budget-config/$', BudgetConfigCreate.as_view()),
    url(r'^dfp/budget-config/listing/$', BudgetConfigListing.as_view()),
    url(r'^dfp/budget-config/edit/(?P<pk>[0-9]+)/$',BudgetConfigEdit.as_view()),
    url(r'^dfp/funding/create/$', FundingCreate.as_view()),
    url(r'^dfp/funding/thematic/listing/$', FundingThematicListing.as_view()),
    url(r'^dfp/funding/year/$', FundingYearListing.as_view()),
    url(r'^dfp/funding/listing/$', FundingListing.as_view()),
    url(r'^dfp/funding/edit/(?P<pk>[0-9]+)/$', FundingDetailView.as_view()),
    url(r'^dfp/project/details/$', DPFProjectViewDetail.as_view()),
    url(r'^dfp/get/name-years/$', GetDateToYearPartner.as_view()),
    url(r'^report/view/$', PartnerReportTable.as_view()),
    url(r'^report/download/$', PartnerDownloadReport.as_view()),
    url(r'^dfp/filters/$', DPFilterData.as_view()),
    url(r'^state-partner-list/(?P<state_list>.+)/$',StateRelatedPartner.as_view()),
    url(r'^create-partner-user-info/$',CreatePartnerUserInfo.as_view()),
    url(r'^partner-user-info-detail/(?P<pk>[0-9]+)/$',PartnerUserInfoDetail.as_view()),
    url(r'^list-partner-user-info/(?P<pk>[0-9]+)/$',PartnerUserInfoList.as_view()),
    #url(r'^partner-database/$',PartnerDatabase.as_view()),
    url(r'^partner-database/$','partner.views.PartnerDatabase'),
    url(r'^create-partner-database/$',export_db),
    url(r'^nature-list/$',NatureOfPartnerList.as_view()),
]




