# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_listing', '0006_dynamicfilter_displaying_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfilter',
            name='filter_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
