# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-11 14:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dynamic_listing', '0007_dynamicfilter_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sub_model', models.CharField(blank=True, max_length=100, null=True)),
                ('model_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dynamicfilter',
            name='displaying_fields',
        ),
        migrations.RemoveField(
            model_name='dynamicfilter',
            name='filtering_fields',
        ),
        migrations.RemoveField(
            model_name='dynamiclisting',
            name='filtering_fields',
        ),
    ]
