# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dynamic_listing', '0008_auto_20171011_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfield',
            name='sub_model',
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_model_type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
