# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dynamic_listing', '0009_auto_20171012_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfilter',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_model_type_dynamic_filter', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dynamicfilter',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamiclisting',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_model_type_dynamic_listing', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dynamiclisting',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
