# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_listing', '0010_auto_20171012_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicfilter',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dynamiclisting',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
