# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_listing', '0011_auto_20171012_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiclisting',
            name='listing_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
