# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_listing', '0012_dynamiclisting_listing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='dynamicfilter',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='dynamiclisting',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
    ]
