# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0002_auto_20170424_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('jsondata', jsonfield.fields.JSONField()),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='SEO friendly url, use only aplhabets and hyphen')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicemonitor',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType'),
        ),
    ]
