# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20170502_1256'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('jsondata', jsonfield.fields.JSONField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
                ('service_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_servicesubtype', to='masterdata.MasterLookUp')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_servicetype', to='masterdata.MasterLookUp')),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_thematicarea', to='masterdata.MasterLookUp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
