# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestion',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
