# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportquestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
