# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20171208_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestion',
            name='location_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
