# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportquestion_location_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestion',
            name='answer_code_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreportquarter',
            name='quarter',
            field=models.IntegerField(blank=True, choices=[(4, 4), (3, 3), (2, 2), (1, 1)], null=True),
        ),
    ]
