# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20171213_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportblock',
            name='dynamic_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.ReportQuestion'),
        ),
    ]
