# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-18 09:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_partnerreportfile_user'),
        ('reports', '0006_auto_20171215_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.PartnerReportQuarter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
