# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-18 09:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
