# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20171218_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreportquarter',
            name='quarter',
            field=models.IntegerField(blank=True, choices=[(4, 'Jan-Mar'), (3, 'Oct-Dec'), (2, 'Jul-Sep'), (1, 'Apr-Jun')], null=True),
        ),
        migrations.AlterField(
            model_name='reportquestion',
            name='answer_code',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='reportquestion',
            name='answer_code_two',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
