# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-17 06:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0009_auto_20171221_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('report_name', models.CharField(max_length=250)),
                ('model_config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('survey_config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mutant_app_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
