# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_aggregatereportconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatereportconfig',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='partnerreportquarter',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='partnerreportyear',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='reportblock',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='reportquestion',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
        migrations.AlterField(
            model_name='reportsurvey',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2),
        ),
    ]
