# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-01-17 05:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20190117_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatereportconfig',
            name='custom_sqlquery_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
