# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-14 07:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20190117_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('jsonid', models.PositiveIntegerField(default=0)),
                ('uuid_lid', models.CharField(blank=True, max_length=500, null=True)),
                ('type_name', models.CharField(blank=True, max_length=500, null=True)),
                ('type_id', models.PositiveIntegerField(default=0)),
                ('ben_fac_loc_id', models.PositiveIntegerField(default=0)),
                ('profile_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('partner_id', models.PositiveIntegerField(default=0)),
                ('submission_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
