# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boundary',
            unique_together=set([('name', 'parent')]),
        ),
    ]
