# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20170310_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boundary',
            unique_together=set([]),
        ),
    ]
