# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_resetactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlookup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.MasterLookUp'),
        ),
    ]
