# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_masterlookup_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundary',
            name='short_name',
        ),
        migrations.AddField(
            model_name='boundary',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hamlet Code'),
        ),
    ]
