# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_auto_20170327_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlookup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
