# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20170404_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlookup',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
