# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('masterdata', '0013_boundary_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
