# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_boundary_ward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlookup',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
