# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20171130_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='cry_admin_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='cry_admin_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
