# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_auto_20180830_1306'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='boundary',
        #     name='cry_admin_id',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
    ]
