# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-10-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0022_remove_boundary_cry_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='cry_admin_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
