# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-12 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
                ('link', models.CharField(blank=True, max_length=512)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userroles.Menus')),
            ],
            options={
                'ordering': ('menu_order',),
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('add', models.IntegerField(blank=True, default=False)),
                ('edit', models.IntegerField(blank=True, default=False)),
                ('view', models.IntegerField(blank=True, default=False)),
                ('delete', models.IntegerField(blank=True, default=False)),
                ('search', models.IntegerField(blank=True, default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userroles.Menus')),
            ],
            options={
                'verbose_name_plural': 'Role Config',
            },
        ),
        migrations.CreateModel(
            name='RoleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={b'unique': b'This role name already existed'}, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=60, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
                ('code', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Role Types',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role_type', models.ManyToManyField(blank=True, to='userroles.RoleTypes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userroles.RoleTypes'),
        ),
    ]
