# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0003_auto_20170315_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name_plural': 'User Role'},
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
