# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0003_auto_20170315_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name_plural': 'User Role'},
        ),
    ]
