# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0004_auto_20170316_1039'),
        ('userroles', '0004_auto_20170316_0913'),
    ]

    operations = [
    ]
