# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0009_roleconfig_organization_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleconfig',
            name='role',
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userroles.RoleTypes'),
        ),
    ]
