# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0010_auto_20170404_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationunit',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='organization_level',
            field=models.IntegerField(blank=True, choices=[(1, b'Country'), (2, b'State'), (3, b'District'), (4, b'Taluk'), (5, b'Mandal'), (6, b'GramaPanchayath'), (7, b'Village')], null=True),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='organization_type',
            field=models.IntegerField(choices=[(1, b'Non-Location'), (2, b'Location')], default=1),
        ),
    ]
