# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-11 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0009_masterlookup_slug'),
        ('userroles', '0011_auto_20170404_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('address1', models.CharField(blank=True, max_length=600, null=True, verbose_name=b'Address1')),
                ('address2', models.CharField(blank=True, max_length=600, null=True, verbose_name=b'Address2')),
                ('contact_no', models.CharField(blank=True, max_length=600, null=True, verbose_name=b'Contact Number')),
                ('pincode', models.CharField(blank=True, max_length=600, null=True, verbose_name=b'Pincode')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object ID')),
                ('boundary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.Boundary')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_address', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Emergency Contact Name')),
                ('relationship', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Emergency Contact Name')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_emergencycontactdetail', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_type', to='masterdata.MasterLookUp')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_type', to='masterdata.MasterLookUp')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userroles',
            name='adhar_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name=b'Date of Birth '),
        ),
        migrations.AddField(
            model_name='userroles',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='pan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='title',
            field=models.IntegerField(blank=True, choices=[(0, b'Mr.'), (1, b'Mrs'), (2, b'Miss'), (3, b'Other')], null=True, verbose_name=b'TITLE_CHOICES'),
        ),
    ]
