# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0014_auto_20170424_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleconfig',
            name='organization_unit',
        ),
    ]
