# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0015_remove_roleconfig_organization_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='office',
            field=models.IntegerField(blank=True, choices=[(1, b'Registered Office'), (2, b'Head Office'), (3, b'Registered & Head Office')], null=True),
        ),
    ]
