# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0016_auto_20170502_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.IntegerField(blank=True, choices=[(1, b'Registered Office'), (2, b'Head Office'), (3, b'Registered & Head Office'), (4, b'Correspondence Office')], null=True),
        ),
    ]
