# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-04 05:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0017_auto_20170503_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
