# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-19 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0020_organizationlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.IntegerField(blank=True, choices=[(1, b'registered_office'), (2, b'head_office'), (3, b'registered_&_head office'), (4, b'correspondence_office'), (5, b'project_manager')], null=True),
        ),
    ]
