# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-05 10:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0022_dynamiclisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiclisting',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='dynamiclisting',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
