# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-19 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0022_auto_20170608_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='link',
            new_name='backend_link',
        ),
        migrations.AddField(
            model_name='menus',
            name='front_link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='menus',
            name='icon',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
