# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-22 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0024_auto_20170622_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, verbose_name=b'SEO friendly url, use only aplhabets and hyphen'),
        ),
    ]
