# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-29 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0025_organizationunit_slug'),
        ('userroles', '0023_auto_20170605_1001'),
    ]

    operations = [
    ]
