# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-29 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0026_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiclisting',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='DynamicListing',
        ),
    ]
