# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0027_auto_20170729_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlocation',
            name='organization_level',
            field=models.IntegerField(blank=True, choices=[(1, b'Country'), (2, b'State'), (3, b'District'), (4, b'Block'), (5, b'GramaPanchayath'), (6, b'Village'), (7, b'Hamlet')], null=True),
        ),
    ]
