# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0030_address_proof'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='address',
        #     name='office',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.MasterLookUp'),
        # ),
    ]
