# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20171130_1114'),
        ('userroles', '0031_auto_20180627_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.MasterLookUp'),
        ),
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.IntegerField(blank=True, choices=[(1, b'registered_office'), (2, b'head_office'), (3, b'registered_&_head office'), (4, b'correspondence_office'), (5, b'project_manager')], null=True),
        ),
    ]
