# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0032_auto_20180629_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='user_type',
            field=models.IntegerField(choices=[(1, b'CRY User'), (2, b'Partner')], default=1),
        ),
    ]
