# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-10-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0033_auto_20180830_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='object ID'),
        ),
    ]
