# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildNeverEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('partner_name', models.CharField(max_length=1000)),
                ('bid', models.PositiveIntegerField()),
                ('child_name', models.CharField(max_length=1000)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('hh_chores_involvement', models.CharField(max_length=1000)),
                ('economic_activities', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'child_never_enrolled',
                'managed': False,
            },
        ),
    ]
