# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-17 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('btype', models.CharField(choices=[('Household', 'Household'), ('Mother', 'Mother')], max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('jsondata', jsonfield.fields.JSONField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
