# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='btype',
            field=models.CharField(choices=[('Household', 'Household'), ('Mother', 'Mother'), ('Child', 'Child')], max_length=100),
        ),
    ]
