# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_boundary_region'),
        ('partner', '0008_auto_20170613_1253'),
        ('beneficiary', '0006_auto_20170609_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaryrelation_partner', to='partner.Partner')),
                ('primary_beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_beneficiary', to='beneficiary.Beneficiary')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.MasterLookUp')),
                ('secondary_beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_beneficiary', to='beneficiary.Beneficiary')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaryrelation',
            unique_together=set([('primary_beneficiary', 'secondary_beneficiary', 'relation')]),
        ),
    ]
