# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-08 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_auto_20170615_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID'),
        ),
    ]
