# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-26 06:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0008_beneficiary_uuid'),
    ]

    operations = [
         migrations.AlterField(
             model_name='beneficiary',
             name='jsondata',
             field=django.contrib.postgres.fields.jsonb.JSONField(),
         ),
    ]
