# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-17 10:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creation_key', models.CharField(blank=True, max_length=30, null=True)),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('app_answer_on', models.DateTimeField(blank=True, null=True)),
                ('app_answer_data', models.PositiveIntegerField(blank=True, null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jsonanswers', to=settings.AUTH_USER_MODEL, verbose_name='jsonuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='inline',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='multy_choice',
            field=models.ManyToManyField(blank=True, related_name='multy_answer_set', to='survey.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='answer text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[(b'T', b'Text Input'), (b'S', b'Select One Choice'), (b'R', b'Radio List'), (b'C', b'Checkbox List'), (b'D', b'Date'), (b'G', b'GPS'), (b'I', b'Image'), (b'V', b'Videos'), (b'E', b'Email'), (b'Cl', b'Cluster'), (b'GD', b'Grid')], max_length=2, verbose_name='question type'),
        ),
    ]
