# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170517_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Project'),
        ),
        migrations.AlterField(
            model_name='appanswerdata',
            name='interface',
            field=models.IntegerField(choices=[(0, b'Web'), (2, b'Android App')], default=0),
        ),
        migrations.AlterField(
            model_name='appanswerdata',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, b'------'), (1, b'Valid'), (2, b'Invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[(b'T', b'Text Input'), (b'S', b'Select One Choice'), (b'R', b'Radio List'), (b'C', b'Checkbox List'), (b'D', b'Date'), (b'G', b'GPS'), (b'I', b'Image'), (b'V', b'Videos'), (b'E', b'Email'), (b'Cl', b'Cluster'), (b'GD', b'Grid'), (b'In', b'Inline')], max_length=2, verbose_name='question type'),
        ),
    ]
