# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20170523_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='validation',
            field=models.IntegerField(blank=True, choices=[(0, b'Digit'), (1, b'Number'), (2, b'Alphabet'), (3, b'Alpha Numeric'), (4, b'No Validation'), (6, b'Mobile Number'), (7, b'Landline'), (8, b'Date'), (9, b'Time'), (10, b'Only Alpha Numeric')], null=True),
        ),
    ]
