# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170706_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
