# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170713_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
