# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-17 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170713_1221'),
        ('survey', '0004_auto_20170710_1403'),
    ]

    operations = [
    ]
