# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-20 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectSurvey',
        ),
    ]
