# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-24 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0025_organizationunit_slug'),
        ('survey', '0008_auto_20170720_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedusersurveymap',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='detailedusersurveymap',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='detailedusersurveymap',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, b'Application level'), (1, b'Location level')], null=True),
        ),
        migrations.RemoveField(
            model_name='detailedusersurveymap',
            name='user',
        ),
        migrations.AddField(
            model_name='detailedusersurveymap',
            name='user',
            field=models.ManyToManyField(to='userroles.UserRoles'),
        ),
    ]
