# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-28 11:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0009_auto_20170724_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('level_name', models.CharField(max_length=25)),
                ('level_code', models.PositiveIntegerField()),
                ('level_api', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyDataEntryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_profile', models.BooleanField(default=True)),
                ('object_id1', models.PositiveIntegerField()),
                ('object_id2', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_loc_bt_or_ft', to='contenttypes.ContentType')),
                ('content_type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_facilty_bt', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='survey',
            name='data_centres',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='project',
        ),
        migrations.AddField(
            model_name='survey',
            name='display_type',
            field=models.CharField(choices=[(b'single', b'single'), (b'multiple', b'multiple')], default=b'multiple', max_length=25),
        ),
        migrations.AlterField(
            model_name='survey',
            name='piriodicity',
            field=models.CharField(choices=[(b'0', b'---NA---'), (b'1', b'Date Wise'), (b'2', b'Weekly'), (b'3', b'Monthly'), (b'4', b'Quarterly'), (b'5', b'Half Yearly'), (b'6', b'Yearly')], default=b'0', max_length=2, verbose_name=b'Periodicity'),
        ),
        migrations.AddField(
            model_name='surveydataentryconfig',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
