# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20170728_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrylevel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
