# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('beneficiary', '0007_auto_20170615_0556'),
        ('survey', '0011_dataentrylevel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIssueTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('userid', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('other_text', models.CharField(blank=True, max_length=255, null=True)),
                ('other_text1', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text1', models.IntegerField(default=0)),
                ('help_text2', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyBeneficiaryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('survey', models.ManyToManyField(to='survey.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detailedusersurveymap',
            name='rule_engine',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsonanswer',
            name='beneficiary',
            field=models.ManyToManyField(blank=True, null=True, to='beneficiary.Beneficiary'),
        ),
        migrations.AddField(
            model_name='jsonanswer',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='jsonanswer',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='jsonanswer',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsonanswer',
            name='response',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='locationtypes',
            name='level_api',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[(b'T', b'Text Input'), (b'S', b'Select One Choice'), (b'R', b'Radio List'), (b'C', b'Checkbox List'), (b'D', b'Date'), (b'G', b'GPS'), (b'I', b'Image'), (b'V', b'Videos'), (b'E', b'Email'), (b'Cl', b'Cluster'), (b'GD', b'Grid'), (b'In', b'Inline'), (b'N', b'None')], max_length=2, verbose_name='question type'),
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
