# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0012_auto_20170729_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveybeneficiarymap',
            old_name='content_type',
            new_name='content_type1',
        ),
        migrations.RenameField(
            model_name='surveybeneficiarymap',
            old_name='object_id',
            new_name='object_id1',
        ),
        migrations.AddField(
            model_name='surveybeneficiarymap',
            name='content_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_facilty', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='surveybeneficiarymap',
            name='object_id2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
