# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20170829_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='skip_question',
        ),
        migrations.AddField(
            model_name='choice',
            name='skip_question',
            field=models.ManyToManyField(blank=True, null=True, related_name='skip_question', to='survey.Question'),
        ),
    ]
