# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 06:57
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20170830_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonanswer',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='jsonanswer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='jsonanswer',
            name='object_id',
        ),
        migrations.AddField(
            model_name='jsonanswer',
            name='cluster',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
