# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20170912_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='piriodicity',
            field=models.CharField(choices=[(b'0', b'---NA---'), (b'1', b'Daily'), (b'2', b'Weekly'), (b'3', b'Monthly'), (b'4', b'Quarterly'), (b'5', b'Half Yearly'), (b'6', b'Yearly')], default=b'0', max_length=2, verbose_name=b'Periodicity'),
        ),
    ]
