# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-22 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170913_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonanswer',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='jsonanswer',
            name='response',
        ),
    ]
