# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-22 09:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20170922_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonanswer',
            name='cluster',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='jsonanswer',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
