# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 11:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20170922_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expiry_age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailedusersurveymap',
            name='rule_engine',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationtypes',
            name='level_api',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
