# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-26 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20170925_1148'),
        
    ]

    operations = [
    ]
