# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-26 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_merge'),
        ('survey', ' 0020_auto_20170926_0614'),
    ]

    operations = [
    ]
