# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_surveypartnerextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('restore_file', models.FileField(blank=True, null=True, upload_to=survey.models.make_dir)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
