# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_surveyrestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrestore',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
