# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0026_auto_20171003_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrestore',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='surveyrestore',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
