# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_boundary_ward_type'),
        ('survey', '0029_auto_20171009_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydump',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='surveydump',
            name='object_id',
        ),
        migrations.AddField(
            model_name='surveydump',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_dump_location', to='masterdata.Boundary'),
        ),
    ]
