# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-22 13:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0030_auto_20171009_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoardResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('partner_level', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('chartdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('facility', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('beneficiary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField(blank=True, choices=[(1, b'Current Week'), (2, b'Current Month'), (3, b'Current Quarter'), (4, b'Current Half-Yearly'), (5, b'Yearly'), (6, b'Fiscal Year')], null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dashboardresponse',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Frequence'),
        ),
        migrations.AddField(
            model_name='dashboardresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
