# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20171024_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardresponse',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, b'CEO'), (2, b'Regional Head'), (3, b'Partner')], null=True),
        ),
    ]
