# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_colorcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version_code', models.IntegerField(default=0)),
                ('version_name', models.CharField(blank=True, max_length=100, null=True)),
                ('force_update', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
