# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_versionupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_grid',
            new_name='is_profile',
        ),
    ]
