# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_auto_20171107_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_grid',
            field=models.BooleanField(default=False),
        ),
    ]
