# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_boundary_ward_type'),
        ('survey', '0037_question_is_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.MasterLookUp'),
        ),
    ]
