# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_survey_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonanswer',
            name='interface',
            field=models.CharField(choices=[(0, b'Web'), (1, b'App'), (2, b'Migrated Data')], default=1, max_length=2),
        ),
    ]
