# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0021_bankaccount_bank'),
        ('survey', '0039_jsonanswer_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardresponse',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='dashboardresponse',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
