# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20171130_1114'),
        ('survey', '0042_auto_20180130_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='states',
            field=models.ManyToManyField(blank=True, null=True, to='masterdata.Boundary'),
        ),
    ]
