# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-30 11:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0043_language_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalJsonAnswer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('creation_key', models.CharField(blank=True, max_length=30, null=True)),
                ('submission_date', models.DateTimeField(blank=True, editable=False)),
                ('app_answer_on', models.DateTimeField(blank=True, null=True)),
                ('app_answer_data', models.PositiveIntegerField(blank=True, null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cluster', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('interface', models.CharField(choices=[(0, b'Web'), (1, b'App'), (2, b'Migrated Data')], default=1, max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Survey')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical json answer',
            },
        ),
    ]
