# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_historicaljsonanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljsonanswer',
            name='interface',
            field=models.CharField(choices=[(b'0', b'Web'), (b'1', b'App'), (b'2', b'Migrated Data')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='jsonanswer',
            name='interface',
            field=models.CharField(choices=[(b'0', b'Web'), (b'1', b'App'), (b'2', b'Migrated Data')], default=1, max_length=2),
        ),
    ]
