# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-28 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_auto_20180509_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljsonanswer',
            name='creation_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jsonanswer',
            name='creation_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
