# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-01 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_auto_20180628_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionvalidation',
            name='other_text1',
        ),
        migrations.AddField(
            model_name='questionvalidation',
            name='validation_condition',
            field=models.CharField(blank=True, choices=[(b'>', b'Greather Than'), (b'<', b'Less Than'), (b'>=', b'Greather Than Equal'), (b'<=', b'Less Than Equal'), (b'==', b'Equals'), (b'!=', b'Not Equal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.IntegerField(choices=[(0, b'Static Survey'), (1, b'Dynamic Survey'), (2, b'Periodic Survey')], default=0),
        ),
    ]
