# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0047_auto_20180801_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_auto_fill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='validation',
            field=models.IntegerField(blank=True, choices=[(0, b'Digit'), (1, b'Number'), (2, b'Alphabet'), (3, b'Alpha Numeric'), (4, b'No Validation'), (6, b'Mobile Number'), (7, b'Landline'), (8, b'Date'), (9, b'Time'), (10, b'Only Alpha Numeric'), (11, b'QuestionBased Validation')], null=True),
        ),
    ]
