# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-08-03 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_auto_20180803_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
