# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-09-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_auto_20180829_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_auto_fill',
        ),
        migrations.AddField(
            model_name='question',
            name='question_auto_fill',
            field=models.ManyToManyField(blank=True, null=True, related_name='_question_question_auto_fill_+', to='survey.Question'),
        ),
    ]
