# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-09-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0053_auto_20180925_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='samandmam',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'Male', max_length=8),
        ),
    ]
