# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-09-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0054_samandmam_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_question', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_auto_fill',
            field=models.ManyToManyField(blank=True, null=True, to='survey.Question'),
        ),
    ]
