# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0056_auto_20181106_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('master_type', models.CharField(blank=True, choices=[(b'BF', b'Beneficiary'), (b'FT', b'Facility')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='master_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
