# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-01-07 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0057_auto_20181128_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_auto_fill',
            field=models.ManyToManyField(blank=True, to='survey.Question'),
        ),
    ]
