# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-01-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0058_auto_20190107_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionautofill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_auto_fill',
        ),
        migrations.AlterField(
            model_name='choice',
            name='skip_question',
            field=models.ManyToManyField(blank=True, related_name='skip_question', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='questions',
            field=models.ManyToManyField(blank=True, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='questionautofill',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autofill_parent_question', to='survey.Question'),
        ),
        migrations.AddField(
            model_name='questionautofill',
            name='question_auto_fill',
            field=models.ManyToManyField(blank=True, related_name='autofillquestion', to='survey.Question'),
        ),
    ]
