# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-13 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_auto_20190313_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionautofill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active'), (1, 'Migrated')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question_sequence', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autofill_parent_question', to='survey.Question')),
                ('question_auto_fill', models.ManyToManyField(blank=True, related_name='autofillquestion', to='survey.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
