# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20170808_0847'),
        ('workflow', '0002_auto_20170901_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_response', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkFlowComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowBatch')),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_next', to='workflow.WorkStateUserRelation')),
                ('previour_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_previous', to='workflow.WorkStateUserRelation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='WorkFlowState',
            new_name='WorkFlow',
        ),
        migrations.RemoveField(
            model_name='workcommondata',
            name='parent',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='flow_state',
            field=models.ManyToManyField(blank=True, null=True, to='workflow.WorkStateUserRelation'),
        ),
        migrations.DeleteModel(
            name='WorkCommonData',
        ),
        migrations.AddField(
            model_name='workflowbatch',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_batch', to='workflow.WorkFlow'),
        ),
        migrations.AddField(
            model_name='workflowbatch',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Project'),
        ),
        migrations.AddField(
            model_name='workflowbatch',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
    ]
