# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-04 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0003_auto_20170903_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowbatch',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
        migrations.RemoveField(
            model_name='workstateuserrelation',
            name='users',
        ),
        migrations.AddField(
            model_name='workstateuserrelation',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
