# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0006_auto_20170906_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowcomment',
            old_name='tag_user',
            new_name='previous_tag_user',
        ),
        migrations.AddField(
            model_name='workflowcomment',
            name='next_tag_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_tagged_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowbatch',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
    ]
