# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0007_auto_20170907_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowbatch',
            name='workflow',
        ),
        migrations.AddField(
            model_name='workflowcomment',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowcomment',
            name='curr_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_curr_state', to='workflow.WorkStateUserRelation'),
        ),
        migrations.AlterField(
            model_name='workflowbatch',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
    ]
