# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20170808_0847'),
        ('workflow', '0008_auto_20170907_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowbatch',
            name='project',
        ),
        migrations.AddField(
            model_name='workflowbatch',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='workflowcomment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Denied'), (1, 'Approved')], null=True),
        ),
        migrations.AlterField(
            model_name='workflowbatch',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
    ]
