# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170908_1241'),
        ('workflow', '0008_auto_20170908_0732'),
    ]

    operations = [
    ]
