# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-08 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170908_1339'),
        ('workflow', '0010_merge'),
    ]

    operations = [
    ]
