# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-11 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0013_auto_20170911_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='curr_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_workflow_curr_state', to='workflow.WorkStateUserRelation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='curr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_commented_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='next_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_workflow_next', to='workflow.WorkStateUserRelation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='next_tag_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_next_tagged_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='previour_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_workflow_previous', to='workflow.WorkStateUserRelation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='previous_tag_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_tagged_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Denied'), (1, 'Approved')], null=True),
        ),
        migrations.AlterField(
            model_name='workflowbatch',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
    ]
