# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20170914_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='types',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'TL'), (2, 'PM'), (3, 'Universal')], null=True),
        ),
        migrations.AlterField(
            model_name='workflowbatch',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowSurveyRelation'),
        ),
    ]
