# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20170920_1559'),
        ('workflow', '0019_auto_20170920_1030'),
    ]

    operations = [
    ]
