# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-22 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20170922_0903'),
        ('workflow', '0022_auto_20170922_1017'),
    ]

    operations = [
    ]
