# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-09 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20171009_0544'),
        ('workflow', '0036_auto_20171005_1739'),
    ]

    operations = [
    ]
