# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_auto_20171012_0544'),
        ('workflow', '0039_auto_20171012_0628'),
    ]

    operations = [
    ]
