# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_merge'),
        ('workflow', '0040_auto_20171011_1239'),
    ]

    operations = [
    ]
