# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20170502_1256'),
        ('partner', '0004_auto_20170504_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='boundary',
            field=models.ManyToManyField(blank=True, null=True, to='masterdata.Boundary'),
        ),
    ]
