# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-19 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170509_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserdetail',
            name='contact_address',
            field=models.BooleanField(default=False, verbose_name='Do the Contact address is same as Project holder/organization chief executive?'),
        ),
    ]
