# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_boundary_region'),
        ('partner', '0007_projectuserdetail_contact_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('other_legal_registration', models.BooleanField(default=False)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_number', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('boundary', models.ManyToManyField(blank=True, null=True, to='masterdata.Boundary')),
                ('community', models.ManyToManyField(blank=True, null=True, related_name='masterlookup_community', to='masterdata.MasterLookUp')),
                ('disbursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_disbursal', to='masterdata.MasterLookUp')),
                ('fla_grm_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_fla_grm_team', to='masterdata.MasterLookUp')),
                ('pre_funding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_funding', to='masterdata.MasterLookUp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='support_since',
            new_name='support_from',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='due_date',
            new_name='exp_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='community',
        ),
        migrations.RemoveField(
            model_name='project',
            name='disbursal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fla_grm_team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='legal_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_legal_registration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pre_funding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='prominent_issues',
        ),
        migrations.RemoveField(
            model_name='project',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='act',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tan',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tin',
        ),
        migrations.AddField(
            model_name='partner',
            name='support_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_reg_type', to='masterdata.MasterLookUp'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_account_type', to='masterdata.MasterLookUp'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_reg_status', to='masterdata.MasterLookUp'),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Project'),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='prominent_issues',
            field=models.ManyToManyField(blank=True, null=True, related_name='masterlookup_issue', to='masterdata.MasterLookUp'),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='theme',
            field=models.ManyToManyField(blank=True, null=True, related_name='masterlookup_theme', to='masterdata.MasterLookUp'),
        ),
        migrations.AddField(
            model_name='program',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Program'),
        ),
    ]
