# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-15 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0008_auto_20170613_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserdetail',
            name='holder_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
