# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_boundary_region'),
        ('partner', '0013_auto_20170720_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('funding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_remark', to='partner.Funding')),
                ('funding_thematic', models.ManyToManyField(blank=True, null=True, related_name='funding_theme_remark', to='partner.BudgetConfig')),
                ('probability_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_funding_remark_probability_status', to='masterdata.MasterLookUp')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_funding_remark_status', to='masterdata.MasterLookUp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
