# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-08 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_boundary_region'),
        ('partner', '0014_fundingremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingremark',
            name='funding_thematic',
        ),
        migrations.AddField(
            model_name='fundingremark',
            name='funding_budget',
            field=models.ManyToManyField(blank=True, null=True, related_name='funding_theme_remark', to='partner.BudgetConfig'),
        ),
        migrations.AddField(
            model_name='fundingremark',
            name='funding_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_theme_name', to='masterdata.MasterLookUp'),
        ),
    ]
