# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-08 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_boundary_region'),
        ('partner', '0015_auto_20170808_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fundingremark',
            name='funding_budget',
        ),
        migrations.RemoveField(
            model_name='fundingremark',
            name='funding_theme',
        ),
        migrations.AddField(
            model_name='fundinglogging',
            name='fund_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.FundingRemark'),
        ),
        migrations.AddField(
            model_name='fundinglogging',
            name='funding_budget',
            field=models.ManyToManyField(blank=True, null=True, related_name='funding_theme_remark', to='partner.BudgetConfig'),
        ),
        migrations.AddField(
            model_name='fundinglogging',
            name='funding_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_theme_name', to='masterdata.MasterLookUp'),
        ),
    ]
