# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-20 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_boundary_ward_type'),
        ('partner', '0016_auto_20170808_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='fund_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlookup_fund_type', to='masterdata.MasterLookUp'),
        ),
    ]
