# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-11 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_bankaccount_fund_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
