# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_auto_20171011_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('report', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
