# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-30 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0019_partnerreportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreportfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
