"""Masterdata Urls."""
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import (BoundaryCreate, BoundaryDetail, MasterLookUpCreate, MasterLookUpDetail, BoundaryList,
                    StateCreate, StateListing, DistrictCreate, DistrictListing, TalukCreate, TalukListing,
                    GPCreate, GPListing, RevenueVillageCreate, RevenueVillageListing,
                    HamletsCreate, HamletsListing, BoundaryCounts, BoundaryLevelCount, BoundaryUpdate,
                    BoundaryActions, StateDetial, StateUpdate, StateAction, BoundarySearch,
                    DistrictDetial, DistrictUpdate, DistrictAction, TalukDetial, TalukUpdate, TalukAction,
                    GPDetial, GPUpdate, GPAction, RevenueVillageDetial, RevenueVillageUpdate,
                    RevenueVillageAction, MasterLookUpActions, HamletsDetial, HamletsUpdate, HamletsAction,
                    MasterLookUpPartnerCreate, BoundaryListWithoutPagination,
                    MasterLookUpGetLocation, BoundaryLiveSearch, MasterLookUpLiveSearch)
from data_import import (
    ImportMaster,  ImportMasterDetails, ImportPartnerDetails)

from location_report import (LocationMasterData,  LocationDataReport)

urlpatterns = [
    url(r'^import-location/$', ImportMaster.as_view()),
    url(r'^import-master/$', ImportMasterDetails.as_view()),
    url(r'^import-partner/$', ImportPartnerDetails.as_view()),
    url(r'^boundary/$', BoundaryCreate.as_view()),
    url(r'^boundary/detail/$', BoundaryDetail.as_view()),
    url(r'^boundary/update/$', BoundaryUpdate.as_view()),
    url(r'^boundary/list/$', BoundaryList.as_view()),
    url(r'^boundary/count/$', BoundaryCounts.as_view()),
    url(r'^boundary/all-level/count/$', BoundaryLevelCount.as_view()),
    url(r'^boundary/actions/$', BoundaryActions.as_view()),
    url(r'^master/lookup/$', MasterLookUpCreate.as_view()),
    url(r'^master/lookup/actions/$', MasterLookUpActions.as_view()),
    url(r'^master/search/$', BoundarySearch.as_view()),
    url(r'^master/lookup/detail/(?P<pk>[0-9]+)/$',
        MasterLookUpDetail.as_view()),
    url(r'^master/partner/create/$', MasterLookUpPartnerCreate.as_view()),
    url(r'^level-2/create/$', StateCreate.as_view()),
    url(r'^level-2/listing/$', StateListing.as_view()),
    url(r'^level-2/detail/$', StateDetial.as_view()),
    url(r'^level-2/update/$', StateUpdate.as_view()),
    url(r'^level-2/action/$', StateAction.as_view()),
    url(r'^level-3/create/$', DistrictCreate.as_view()),
    url(r'^level-3/listing/$', DistrictListing.as_view()),
    url(r'^level-3/detail/$', DistrictDetial.as_view()),
    url(r'^level-3/update/$', DistrictUpdate.as_view()),
    url(r'^level-3/action/$', DistrictAction.as_view()),
    url(r'^level-4/create/$', TalukCreate.as_view()),
    url(r'^level-4/listing/$', TalukListing.as_view()),
    url(r'^level-4/detail/$', TalukDetial.as_view()),
    url(r'^level-4/update/$', TalukUpdate.as_view()),
    url(r'^level-4/action/$', TalukAction.as_view()),
    url(r'^level-5/create/$', GPCreate.as_view()),
    url(r'^level-5/listing/$', GPListing.as_view()),
    url(r'^level-5/detail/$', GPDetial.as_view()),
    url(r'^level-5/update/$', GPUpdate.as_view()),
    url(r'^level-5/action/$', GPAction.as_view()),
    url(r'^level-6/create/$', RevenueVillageCreate.as_view()),
    url(r'^level-6/listing/$', RevenueVillageListing.as_view()),
    url(r'^level-6/detail/$', RevenueVillageDetial.as_view()),
    url(r'^level-6/update/$', RevenueVillageUpdate.as_view()),
    url(r'^level-6/action/$', RevenueVillageAction.as_view()),
    url(r'^level-7/create/$', HamletsCreate.as_view()),
    url(r'^level-7/listing/$', HamletsListing.as_view()),
    url(r'^level-7/detail/$', HamletsDetial.as_view()),
    url(r'^level-7/update/$', HamletsUpdate.as_view()),
    url(r'^level-7/action/$', HamletsAction.as_view()),
    url(r'^boundary/no-pagination/$', BoundaryListWithoutPagination.as_view()),
    url(r'^master/lookup/location-type/listing/$',
        MasterLookUpGetLocation.as_view()),
    url(r'^live/search/$', BoundaryLiveSearch.as_view()),
    url(r'^live/lookup/search/$', MasterLookUpLiveSearch.as_view()),
    url(r'^report/data/$', LocationMasterData.as_view()),
    url(r'^report/list/$', LocationDataReport.as_view())]
